# NOTE: update this with your service name
service: serverless-boilerplate-april-2019

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-mocha-plugin
  - serverless-dynamodb-local

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

#functions:
#  api/v1/users/example:
#    handler: handlers/api/v1/users/example.default
#    events:
#      - http:
#          path: '/'
#          cors: true
#          method: get
